language: objective-c
osx_image: xcode7.2

before_install:
  - bash update_carthage.sh 0.12
  - carthage update --no-use-binaries --platform iOS 
script: 
  - xcodebuild test -project TravisViewerIOS.xcodeproj -scheme TravisViewerIOSTests -destination 'platform=iOS Simulator,OS=9.2,name=iPhone 6s' -sdk iphonesimulator -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash)